### ISSUE TITLE
Return Statement Is Not Within Curly Braces For 'handleFilterChange' Function

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/react-hooks-state-arrays#10]
### Canvas Link

https://learning.flatironschool.com/courses/5285/assignments/172499?module_item_id=376327

### Concern

There is clearly something missing with the 'return' statement present for this section of the lab, please look and consider if there is a typo because it doesn't make sense if the 'SpicyFoodList' has TWO return statements, which doesn't seem to be the case, looks like a curly brace is missing for this:

```
function handleFilterChange(event) {
  setFilterBy(event.target.value);
}

return (
  <select name="filter" onChange={handleFilterChange}>
    <option value="All">All</option>
    <option value="American">American</option>
    <option value="Sichuan">Sichuan</option>
    <option value="Thai">Thai</option>
    <option value="Mexican">Mexican</option>
  </select>
);
```

**Comment by AlveeM** [comment]
Hi, thanks for submitting the issue.

The `return` statement is within the `SpicyFoodList` function here. This function is a React Component since it's returning JSX. 

Here's the full source code in the SpicyFoodList.js file for reference:
```javascript
function SpicyFoodList() {
  const [foods, setFoods] = useState(spicyFoods);

  function handleAddFood() {
    const newFood = getNewSpicyFood();
    console.log(newFood);
  }

  const foodList = foods.map((food) => (
    <li key={food.id}>
      {food.name} | Heat: {food.heatLevel} | Cuisine: {food.cuisine}
    </li>
  ));

  return (
    <div>
      <button onClick={handleAddFood}>Add New Food</button>
      <ul>{foodList}</ul>
    </div>
  );
}```

If you're unsure what the code is doing, please reach out to your coach or instructor.
