### ISSUE TITLE
Chokidar bug on install

### ISSUE THREAD

**Issue by BrawnyVolt** [learn-co-curriculum/react-hooks-state-arrays#3]
### Canvas Link

https://learning.flatironschool.com/courses/4377/assignments/142182?module_item_id=297724

### Concern

On fresh git clone, after npm i it throws an error regarding chokidar. Newest version doesn't work with node v14<

update package.json to
```
{
  "name": "react-hooks-state-arrays",
  "version": "0.1.0",
  "engines": {
    "node": "<=14.0.0"
  },
  "private": true,
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1"
  },
  "scripts": {
    "start": "react-scripts start"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

### Additional Context

Compiled with warnings.
src/components/SpicyFoodList.js
  Line 5:17:  'setFoods' is assigned a value but never used  no-unused-vars
Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
/home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js:17
throw new Error(
^
Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/watcherManager.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/watchpack.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/webpack/lib/webpack.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/react-scripts/scripts/start.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/watcherManager.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/watchpack.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/webpack/lib/webpack.js
- /home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/react-scripts/scripts/start.js
    at Object.<anonymous> (/home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/chokidar.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/stev/phase-2/teststuffhere/react-hooks-state-arrays/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

### Suggested Changes

update package.json to
```
{
  "name": "react-hooks-state-arrays",
  "version": "0.1.0",
  "engines": {
    "node": "<=14.0.0"
  },
  "private": true,
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1"
  },
  "scripts": {
    "start": "react-scripts start"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by graciemcguire** [comment]
Hi @BrawnyVolt,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you want to provide further detail about the steps required to reproduce the issue, and any additional relevant information about your development environment, I'd be happy to take a second look!

As always, thanks for contributing! 💙
