### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by jenipdang** [learn-co-curriculum/react-hooks-state-arrays#4]
### Canvas Link

https://learning.flatironschool.com/courses/4696/assignments/138248?module_item_id=287002

### Concern

Typo at the end near conclusion. Should be handleClick not handleLiClick

const foodList = foodsToDisplay.map((food) => (
  <li key={food.id} onClick={() => **_handleLiClick(_**food.id)}>
    {food.name} | Heat: {food.heatLevel} | Cuisine: {food.cuisine}
  </li>
));

**Comment by ihollander** [comment]
Hi @jenipdang - in this example, `handleLiClick` refers to a named function that we defined earlier on in the readme:

```jsx
function handleLiClick(id) {
  const newFoodArray = foods.map((food) => {
    if (food.id === id) {
      return {
        ...food,
        heatLevel: food.heatLevel + 1,
      };
    } else {
      return food;
    }
  });
  setFoods(newFoodArray);
}
```

You can see the full working example in the solution branch of this repository: https://github.com/learn-co-curriculum/react-hooks-state-arrays/blob/solution/src/components/SpicyFoodList.js
