### ISSUE TITLE
Include 'handleAddFood' Function Within Actual Prompt

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/react-hooks-state-arrays#9]
### Canvas Link

https://learning.flatironschool.com/courses/5285/assignments/172499?module_item_id=376327

### Concern

This prompt should be more directed to the specific function that's asked to be modified:
```
The starter code for this component is in SpicyFoodList.js. Before we walk through the solution, see if you can get this working by adding a new spicy food to the array when the button is clicked.
```

There is so much going on within the files within this lab that an additional note of where to even start is just flat out needed here if you're going to prompt someone to try to do a revision since there's so much boilerplate code present to begin with.

### Suggested Changes

This should be changed to this:
```
The starter code for this component is in SpicyFoodList.js. Before we walk through the solution, see if you can get this working by adding a new spicy food to the array when the button is clicked within the 'handleAddFood' function
```

**Comment by AlveeM** [comment]
Hi, thanks for the suggestion. 

We want the student to figure out the data flow when the user interacts with the app. Since there's a solution provided in the lesson, we won't be expanding the prompt.
